import type { Metadata } from 'next';
import './globals.css';
import { Navbar } from '@/components/Navbar';
import { ClientProvider } from './clientProvider';
import { Footer } from '@/components/Footer';
import { DbInitializer } from '@/components/DbInitializer';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased bg-primary-background text-primary min-h-screen`}>
                {/* Composant qui s'assure que la DB est initialisée côté serveur */}
                <DbInitializer />
                <ClientProvider>
                    <Navbar />
                    {children}
                    <Footer />
                </ClientProvider>
            </body>
        </html>
    );
}
