name: Docker Image CI

on:
  # pull_request:
  #   branches: [ "main" ]
  #   types: ["closed"]
  push:
    branches: [ "main" ]

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - uses: actions/checkout@v4
    - name: Set up Docker image tag
      id: vars
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wiibleyde-time4earth:${{ env.IMAGE_TAG }} --tag wiibleyde-time4earth:latest

    - name: Push the Docker image
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - run: docker tag wiibleyde-time4earth:${{ env.IMAGE_TAG }} ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g'):${{ env.IMAGE_TAG }}
    - run: docker tag wiibleyde-time4earth:latest ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g'):latest
    - run: docker push ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g'):${{ env.IMAGE_TAG }}
    - run: docker push ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g'):latest